#pragma once

#include "../NT.h"

EXTERN_C_START

#pragma region ASSEMBLY_STORAGE_MAP_ENTRY[64/32]

typedef struct _ASSEMBLY_STORAGE_MAP_ENTRY64
{
    ULONG Flags;
    UNICODE_STRING64 DosPath;
    VOID* POINTER_64 Handle;
} ASSEMBLY_STORAGE_MAP_ENTRY64, *PASSEMBLY_STORAGE_MAP_ENTRY64;

typedef struct _ASSEMBLY_STORAGE_MAP_ENTRY32
{
    ULONG Flags;
    UNICODE_STRING32 DosPath;
    VOID* POINTER_32 Handle;
} ASSEMBLY_STORAGE_MAP_ENTRY32, *PASSEMBLY_STORAGE_MAP_ENTRY32;

#pragma endregion

#pragma region ASSEMBLY_STORAGE_MAP[64/32]

typedef struct _ASSEMBLY_STORAGE_MAP64
{
    ULONG Flags;
    ULONG AssemblyCount;
    ASSEMBLY_STORAGE_MAP_ENTRY64* POINTER_64* AssemblyArray;
} ASSEMBLY_STORAGE_MAP64, *PASSEMBLY_STORAGE_MAP64;

typedef struct _ASSEMBLY_STORAGE_MAP32
{
    ULONG Flags;
    ULONG AssemblyCount;
    ASSEMBLY_STORAGE_MAP_ENTRY32* POINTER_32* AssemblyArray;
} ASSEMBLY_STORAGE_MAP32, *PASSEMBLY_STORAGE_MAP32;

#pragma endregion

#pragma region ACTIVATION_CONTEXT[64/32]

typedef struct _ACTIVATION_CONTEXT64
{
    LONG RefCount;
    ULONG Flags;
    ACTIVATION_CONTEXT_DATA* POINTER_64 ActivationContextData;
    VOID* POINTER_64 NotificationRoutine; // PACTIVATION_CONTEXT_NOTIFY_ROUTINE
    VOID* POINTER_64 NotificationContext;
    ULONG SentNotifications[8];
    ULONG DisabledNotifications[8];
    ASSEMBLY_STORAGE_MAP64 StorageMap;
    ASSEMBLY_STORAGE_MAP_ENTRY64* POINTER_64 InlineStorageMapEntries[32];
} ACTIVATION_CONTEXT64, *PACTIVATION_CONTEXT64;

typedef struct _ACTIVATION_CONTEXT32
{
    LONG RefCount;
    ULONG Flags;
    ACTIVATION_CONTEXT_DATA* POINTER_32 ActivationContextData;
    VOID* POINTER_32 NotificationRoutine; // PACTIVATION_CONTEXT_NOTIFY_ROUTINE
    VOID* POINTER_32 NotificationContext;
    ULONG SentNotifications[8];
    ULONG DisabledNotifications[8];
    ASSEMBLY_STORAGE_MAP32 StorageMap;
    ASSEMBLY_STORAGE_MAP_ENTRY32* POINTER_32 InlineStorageMapEntries[32];
} ACTIVATION_CONTEXT32, *PACTIVATION_CONTEXT32;

#pragma region [RTL_]ACTIVATION_CONTEXT_STACK[_FRAME][64/32]

typedef struct _RTL_ACTIVATION_CONTEXT_STACK_FRAME64 RTL_ACTIVATION_CONTEXT_STACK_FRAME64, *PRTL_ACTIVATION_CONTEXT_STACK_FRAME64;
typedef struct _RTL_ACTIVATION_CONTEXT_STACK_FRAME32 RTL_ACTIVATION_CONTEXT_STACK_FRAME32, *PRTL_ACTIVATION_CONTEXT_STACK_FRAME32;

struct _RTL_ACTIVATION_CONTEXT_STACK_FRAME64
{
    RTL_ACTIVATION_CONTEXT_STACK_FRAME64* POINTER_64 Previous;
    ACTIVATION_CONTEXT64* POINTER_64 ActivationContext;
    ULONG Flags;
};

struct _RTL_ACTIVATION_CONTEXT_STACK_FRAME32
{
    RTL_ACTIVATION_CONTEXT_STACK_FRAME32* POINTER_32 Previous;
    ACTIVATION_CONTEXT32* POINTER_32 ActivationContext;
    ULONG Flags;
};

typedef struct _ACTIVATION_CONTEXT_STACK64
{
    RTL_ACTIVATION_CONTEXT_STACK_FRAME64* POINTER_64 ActiveFrame;
    LIST_ENTRY64 FrameListCache;
    ULONG Flags;
    ULONG NextCookieSequenceNumber;
    ULONG StackId;
} ACTIVATION_CONTEXT_STACK64, *PACTIVATION_CONTEXT_STACK64;

typedef struct _ACTIVATION_CONTEXT_STACK32
{
    RTL_ACTIVATION_CONTEXT_STACK_FRAME32* POINTER_32 ActiveFrame;
    LIST_ENTRY32 FrameListCache;
    ULONG Flags;
    ULONG NextCookieSequenceNumber;
    ULONG StackId;
} ACTIVATION_CONTEXT_STACK32, *PACTIVATION_CONTEXT_STACK32;

#pragma endregion

#pragma endregion

EXTERN_C_END
